apiVersion: v1
kind: Service
metadata:
  name: auth-ms
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: auth-ms
    tier: backend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-ms
      tier: backend
  template:
    metadata:
      labels:
        app: auth-ms
        tier: backend
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              key: MYSQL_DATABASE_NAME
              name: env-configmap
        - name: MYSQL_HOSTNAME
          valueFrom:
            configMapKeyRef:
              key: MYSQL_HOSTNAME
              name: env-configmap
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_ROOT_PASSWORD
              name: secrets
        - name: MYSQL_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              key: MYSQL_ROOT_USERNAME
              name: secrets
        - name: PORT
          value: '80'
        image: 7rocky/auth-ms
        imagePullPolicy: Always
        name: auth-ms
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            memory: 64Mi
      initContainers:
      - command:
        - 'sh'
        - '-c'
        - 'until nslookup $MYSQL_HOSTNAME; do :; sleep 2; done;'
        env:
        - name: MYSQL_HOSTNAME
          valueFrom:
            configMapKeyRef:
              key: MYSQL_HOSTNAME
              name: env-configmap
        image: busybox:1.28
        name: init-auth-ms