apiVersion: v1
kind: Service
metadata:
  name: orchestrator-ms
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: orchestrator-ms
    tier: backend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator-ms
      tier: backend
  template:
    metadata:
      labels:
        app: orchestrator-ms
        tier: backend
    spec:
      containers:
      - env:
        - name: AUTH_MS_HOSTNAME
          valueFrom:
            configMapKeyRef:
              key: AUTH_MS_HOSTNAME
              name: env-configmap
        - name: MEASURE_MS_HOSTNAME
          valueFrom:
            configMapKeyRef:
              key: MEASURE_MS_HOSTNAME
              name: env-configmap
        - name: MICROCONTROLLERS_MS_HOSTNAME
          valueFrom:
            configMapKeyRef:
              key: MICROCONTROLLERS_MS_HOSTNAME
              name: env-configmap
        - name: PORT
          value: '80'
        image: 7rocky/orchestrator-ms
        imagePullPolicy: Always
        name: orchestrator-ms
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            memory: 16Mi
