apiVersion: v1
kind: Service
metadata:
  name: stats-ms
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: stats-ms
    tier: backend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stats-ms
      tier: backend
  template:
    metadata:
      labels:
        app: stats-ms
        tier: backend
    spec:
      containers:
      - env:
        - name: MONGO_DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              key: MONGO_DATABASE_NAME
              name: env-configmap
        - name: MONGO_HOSTNAME
          valueFrom:
            configMapKeyRef:
              key: MONGO_HOSTNAME
              name: env-configmap
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              key: MONGO_INITDB_ROOT_USERNAME
              name: secrets
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MONGO_INITDB_ROOT_PASSWORD
              name: secrets
        - name: QUEUE_HUMIDITY_NAME
          valueFrom:
            configMapKeyRef:
              key: QUEUE_HUMIDITY_NAME
              name: env-configmap
        - name: QUEUE_LIGHT_NAME
          valueFrom:
            configMapKeyRef:
              key: QUEUE_LIGHT_NAME
              name: env-configmap
        - name: QUEUE_TEMPERATURE_NAME
          valueFrom:
            configMapKeyRef:
              key: QUEUE_TEMPERATURE_NAME
              name: env-configmap
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              key: RABBITMQ_DEFAULT_USER
              name: secrets
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              key: RABBITMQ_DEFAULT_PASS
              name: secrets
        - name: RABBITMQ_HOSTNAME
          valueFrom:
            configMapKeyRef:
              key: RABBITMQ_HOSTNAME
              name: env-configmap
        image: 7rocky/stats-ms
        imagePullPolicy: Always
        name: stats-ms
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            memory: 16Mi
      initContainers:
      - command:
        - 'sh'
        - '-c'
        - 'until nslookup $MONGO_HOSTNAME && nslookup $RABBITMQ_HOSTNAME; do :; sleep 2; done;'
        env:
        - name: MONGO_HOSTNAME
          valueFrom:
            configMapKeyRef:
              key: MONGO_HOSTNAME
              name: env-configmap
        - name: RABBITMQ_HOSTNAME
          valueFrom:
            configMapKeyRef:
              key: RABBITMQ_HOSTNAME
              name: env-configmap
        image: busybox:1.28
        name: init-stats-ms
