apiVersion: apps/v1
kind: Deployment
metadata:
  name: humidity-ms
spec:
  selector:
    matchLabels:
      app: humidity-ms
      tier: backend
      track: stable
  replicas: 3
  template:
    metadata:
      labels:
        app: humidity-ms
        tier: backend
        track: stable
    spec:
      containers:
      - name: humidity-ms
        image: 7rocky/humidity-ms
        env:
        - name: ARDUINO
          value: "192.168.1.50"
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "256Mi"
            cpu: "100m"
          requests:
            memory: "64Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: humidity-ms
spec:
  selector:
    app: humidity-ms
    tier: backend
    track: stable
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
