apiVersion: v1
kind: Service
metadata:
  name: microcontrollers-ms
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: microcontrollers-ms
    tier: backend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microcontrollers-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microcontrollers-ms
      tier: backend
  template:
    metadata:
      labels:
        app: microcontrollers-ms
        tier: backend
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              key: MYSQL_DATABASE_NAME
              name: env-configmap
        - name: MYSQL_HOSTNAME
          valueFrom:
            configMapKeyRef:
              key: MYSQL_HOSTNAME
              name: env-configmap
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: MYSQL_ROOT_PASSWORD
              name: env-configmap
        - name: PORT
          value: '80'
        image: 7rocky/microcontrollers-ms
        imagePullPolicy: Always
        name: microcontrollers-ms
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            memory: 16Mi
