apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator-ms
spec:
  selector:
    matchLabels:
      app: orchestrator-ms
      tier: backend
      track: stable
  replicas: 3
  template:
    metadata:
      labels:
        app: orchestrator-ms
        tier: backend
        track: stable
    spec:
      containers:
      - name: orchestrator-ms
        image: 7rocky/orchestrator-ms
        env:
        - name: PORT
          value: "80"
        ports:
        - name: http
          containerPort: 80
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
          requests:
            memory: "16Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator-ms
spec:
  selector:
    app: orchestrator-ms
    tier: backend
    track: stable
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
